scalar GraphQLDate

type Employee {
  id: Int
  firstName: String
  lastName: String
  age: Int
  dateOfJoining: GraphQLDate
  title: String
  department: String
  EmployeeType: String
  currentStatus: Boolean
}

input EmployeeInput {
  firstName: String
  lastName: String
  age: Int
  dateOfJoining: GraphQLDate
  title: String
  department: String
  EmployeeType: String
  currentStatus: Boolean
}

type Query {
  employeeList: [Employee]
  employeeDetail(id: Int): Employee
}

type Mutation {
  createEmployee(newEmployee: EmployeeInput): Employee
  updateEmployee(id: Int, newEmployee: EmployeeInput): Employee
  deleteEmployee(id: Int): Boolean

}
