scalar GraphQLDate

type Employee {
  id: Int
  firstName: String
  lastName: String
  age: Int
  dob: GraphQLDate
  dateOfJoining: GraphQLDate
  title: String
  department: String
  EmployeeType: String
  currentStatus: Boolean
  retirementDetails: RetirementDetails
}

type RetirementDetails {
  dateOfRetirement: GraphQLDate
  yearsLeft: String
  monthsLeft: String
  daysLeft: String
  isUpcoming: Boolean
}

input EmployeeInput {
  firstName: String
  lastName: String
  age: Int
  dob: GraphQLDate
  dateOfJoining: GraphQLDate
  title: String
  department: String
  EmployeeType: String
  currentStatus: Boolean
}

type Query {
  employeeList(type: String, retirementFilter: Boolean): [Employee]
  employeeDetail(id: Int): Employee
}

type Mutation {
  createEmployee(newEmployee: EmployeeInput): Employee
  updateEmployee(id: Int, newEmployee: EmployeeInput): Employee
  deleteEmployee(id: Int): Boolean

}
